name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Updates every night
  workflow_dispatch: # Allows you to run it manually
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: JainamSavla
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          
          # This replaces your "Top Languages" card
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          
          # This adds extra punch to your profile
          plugin_lines: yes
          plugin_habits: yes
          plugin_habits_charts: yes
